kind: Deployment 
apiVersion: apps/v1
metadata:
  name: chatapp-backend
  namespace: chatapp
spec:
  selector:
    matchLabels:
      app: chatapp-backend
  replicas: 1
  template:
    metadata:
      name: chatapp-backend
      namespace: chatapp
      labels: 
        app: chatapp-backend
    spec:
      containers:
      - name: chatapp-backend
        image: prajwalkumar1453/chatapp-backend:latest
        ports:
          - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://chatappuser:chatapppass@mongosvc:27017/chatApp?authSource=chatApp"
        - name: PORT 
          value: "5001"
        - name: JWT_SECRET
          value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MzQ3MjA5MzAsImV4cCI6MTc2NjI1NjkzMCwiYXVkIjoidHJhaW53aXRoc2h1YmhhbS5jb20iLCJzdWIiOiJqcm9ja2V0QGV4YW1wbGUuY29tIiwiR2l2ZW5OYW1lIjoiQWZ6YWwiLCJTdXJuYW1lIjoiUm9ja2V0IiwiRW1haWwiOiJqcm9ja2V0QGV4YW1wbGUuY29tIiwiUm9sZSI6WyJEZXZPcHMiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.ehelBbUU2IFJ8M5xzQL_UFatMxCMSojAOqWQaZQgrwk"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
