kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: chatapp-frontend
  namespace: chatapp
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      name: chatapp-frontend
      namespace: chatapp
      labels: 
        app: chatapp-frontend
    spec: 
      containers:
      - name: chatapp-frontend
        image: prajwalkumar1453/chatapp-frontend:latest
        ports:  
        - containerPort: 80
        resources:  
          requests: 
            cpu: 100m 
            memory: 100Mi
          limits:
            cpu: 100m 
            memory: 100Mi