apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chatapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /tmp/mongo-data
