kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: mongo-deployment
  namespace: chatapp
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      namespace: chatapp
      labels:   
        app: mongo
    spec: 
      containers:
      - name: mongo
        image: mongo:latest
        ports:  
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: root
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: mongo-data
        persistentVolumeClaim: 
          claimName: mongo-pvc
      - name: mongo-init
        configMap:
          name: mongo-init-script

